//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coffee_shop
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int ReportID { get; set; }
        public Nullable<int> SaleID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public decimal Revenue { get; set; }
    
        public virtual Sale Sale { get; set; }
    }
}
